---

- name: Who am I?
  debug:
    msg: "{{ SP_MACHINE_NAME }}"

- name: Make sure the Homebrew directory exists
  file:
    path: /usr/local
    state: directory
    mode: 0775
    group: admin

- name: Install Homebrew with git
  git:
    repo: https://github.com/Homebrew/homebrew.git
    dest: /usr/local
    version: master
    force: yes

- name: Configure brew taps
  homebrew_tap:
    tap: "{{ item }}"
    state: present
  with_items:
    - homebrew/dupes
    - homebrew/versions

- name: Update Homebrew
  homebrew:
    update_homebrew: yes

- name: Set package manager to homebrew
  set_fact:
    ansible_pkg_mgr: homebrew
