---

- name: Set OS family for LinuxMint
  hosts: all
  tasks:
    - name: Identify LinuxMint as Debian so we can select the correct group
      set_fact:
        ansible_os_family: "Debian"
      when: ansible_os_family == "Debian" or ansible_os_family == "Linuxmint"

- name: Run basic OS setup
  hosts: all
  gather_facts: false
  vars_files:
      - "vars/{{ ansible_os_family }}.yml"
  roles:
    - os-setup