---

- name: Identify which group to run
  hosts: all
  tasks:
    - name: Identify LinuxMint as Debian so we can select the correct group
      set_fact:
        ansible_os_family: "Debian"
      when: ansible_os_family == "Debian" or ansible_os_family == "Linuxmint"

    - name: Determine OS
      group_by:
        key: "{{ ansible_os_family }}"

- name: Run Debian playbook
  hosts: Debian
  tasks:
    - name: Identify yourself
      debug:
        msg: "{{ ansible_os_family }}"

- name: Run OSX playbook
  hosts: Darwin
  tasks:
    - name: Identify yourself
      debug:
        msg: "OSX and such"